# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.24.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.24.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Oktaviano/Development/rendering-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Oktaviano/Development/rendering-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.24.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.24.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Oktaviano/Development/rendering-engine/CMakeFiles /Users/Oktaviano/Development/rendering-engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Oktaviano/Development/rendering-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SillyEngine

# Build rule for target.
SillyEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SillyEngine
.PHONY : SillyEngine

# fast build rule for target.
SillyEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/build
.PHONY : SillyEngine/fast

#=============================================================================
# Target rules for targets named STB_IMAGE

# Build rule for target.
STB_IMAGE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 STB_IMAGE
.PHONY : STB_IMAGE

# fast build rule for target.
STB_IMAGE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STB_IMAGE.dir/build.make CMakeFiles/STB_IMAGE.dir/build
.PHONY : STB_IMAGE/fast

#=============================================================================
# Target rules for targets named GLAD

# Build rule for target.
GLAD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GLAD
.PHONY : GLAD

# fast build rule for target.
GLAD/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/build
.PHONY : GLAD/fast

CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.o: CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.i: CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.s: CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.o: build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.i: build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.s: build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.o: cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.i: cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.s: cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

core/Engine.o: core/Engine.cpp.o
.PHONY : core/Engine.o

# target to build an object file
core/Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Engine.cpp.o
.PHONY : core/Engine.cpp.o

core/Engine.i: core/Engine.cpp.i
.PHONY : core/Engine.i

# target to preprocess a source file
core/Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Engine.cpp.i
.PHONY : core/Engine.cpp.i

core/Engine.s: core/Engine.cpp.s
.PHONY : core/Engine.s

# target to generate assembly for a file
core/Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Engine.cpp.s
.PHONY : core/Engine.cpp.s

core/Framebuffer.o: core/Framebuffer.cpp.o
.PHONY : core/Framebuffer.o

# target to build an object file
core/Framebuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Framebuffer.cpp.o
.PHONY : core/Framebuffer.cpp.o

core/Framebuffer.i: core/Framebuffer.cpp.i
.PHONY : core/Framebuffer.i

# target to preprocess a source file
core/Framebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Framebuffer.cpp.i
.PHONY : core/Framebuffer.cpp.i

core/Framebuffer.s: core/Framebuffer.cpp.s
.PHONY : core/Framebuffer.s

# target to generate assembly for a file
core/Framebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Framebuffer.cpp.s
.PHONY : core/Framebuffer.cpp.s

core/ImageLoader.o: core/ImageLoader.cpp.o
.PHONY : core/ImageLoader.o

# target to build an object file
core/ImageLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/ImageLoader.cpp.o
.PHONY : core/ImageLoader.cpp.o

core/ImageLoader.i: core/ImageLoader.cpp.i
.PHONY : core/ImageLoader.i

# target to preprocess a source file
core/ImageLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/ImageLoader.cpp.i
.PHONY : core/ImageLoader.cpp.i

core/ImageLoader.s: core/ImageLoader.cpp.s
.PHONY : core/ImageLoader.s

# target to generate assembly for a file
core/ImageLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/ImageLoader.cpp.s
.PHONY : core/ImageLoader.cpp.s

core/Input.o: core/Input.cpp.o
.PHONY : core/Input.o

# target to build an object file
core/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Input.cpp.o
.PHONY : core/Input.cpp.o

core/Input.i: core/Input.cpp.i
.PHONY : core/Input.i

# target to preprocess a source file
core/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Input.cpp.i
.PHONY : core/Input.cpp.i

core/Input.s: core/Input.cpp.s
.PHONY : core/Input.s

# target to generate assembly for a file
core/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Input.cpp.s
.PHONY : core/Input.cpp.s

core/Mesh.o: core/Mesh.cpp.o
.PHONY : core/Mesh.o

# target to build an object file
core/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Mesh.cpp.o
.PHONY : core/Mesh.cpp.o

core/Mesh.i: core/Mesh.cpp.i
.PHONY : core/Mesh.i

# target to preprocess a source file
core/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Mesh.cpp.i
.PHONY : core/Mesh.cpp.i

core/Mesh.s: core/Mesh.cpp.s
.PHONY : core/Mesh.s

# target to generate assembly for a file
core/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Mesh.cpp.s
.PHONY : core/Mesh.cpp.s

core/Model.o: core/Model.cpp.o
.PHONY : core/Model.o

# target to build an object file
core/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Model.cpp.o
.PHONY : core/Model.cpp.o

core/Model.i: core/Model.cpp.i
.PHONY : core/Model.i

# target to preprocess a source file
core/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Model.cpp.i
.PHONY : core/Model.cpp.i

core/Model.s: core/Model.cpp.s
.PHONY : core/Model.s

# target to generate assembly for a file
core/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Model.cpp.s
.PHONY : core/Model.cpp.s

core/Shader.o: core/Shader.cpp.o
.PHONY : core/Shader.o

# target to build an object file
core/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Shader.cpp.o
.PHONY : core/Shader.cpp.o

core/Shader.i: core/Shader.cpp.i
.PHONY : core/Shader.i

# target to preprocess a source file
core/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Shader.cpp.i
.PHONY : core/Shader.cpp.i

core/Shader.s: core/Shader.cpp.s
.PHONY : core/Shader.s

# target to generate assembly for a file
core/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Shader.cpp.s
.PHONY : core/Shader.cpp.s

core/Window.o: core/Window.cpp.o
.PHONY : core/Window.o

# target to build an object file
core/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Window.cpp.o
.PHONY : core/Window.cpp.o

core/Window.i: core/Window.cpp.i
.PHONY : core/Window.i

# target to preprocess a source file
core/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Window.cpp.i
.PHONY : core/Window.cpp.i

core/Window.s: core/Window.cpp.s
.PHONY : core/Window.s

# target to generate assembly for a file
core/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/Window.cpp.s
.PHONY : core/Window.cpp.s

core/components/Camera.o: core/components/Camera.cpp.o
.PHONY : core/components/Camera.o

# target to build an object file
core/components/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/components/Camera.cpp.o
.PHONY : core/components/Camera.cpp.o

core/components/Camera.i: core/components/Camera.cpp.i
.PHONY : core/components/Camera.i

# target to preprocess a source file
core/components/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/components/Camera.cpp.i
.PHONY : core/components/Camera.cpp.i

core/components/Camera.s: core/components/Camera.cpp.s
.PHONY : core/components/Camera.s

# target to generate assembly for a file
core/components/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/components/Camera.cpp.s
.PHONY : core/components/Camera.cpp.s

core/experimental_vertices_model_loader.o: core/experimental_vertices_model_loader.cpp.o
.PHONY : core/experimental_vertices_model_loader.o

# target to build an object file
core/experimental_vertices_model_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/experimental_vertices_model_loader.cpp.o
.PHONY : core/experimental_vertices_model_loader.cpp.o

core/experimental_vertices_model_loader.i: core/experimental_vertices_model_loader.cpp.i
.PHONY : core/experimental_vertices_model_loader.i

# target to preprocess a source file
core/experimental_vertices_model_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/experimental_vertices_model_loader.cpp.i
.PHONY : core/experimental_vertices_model_loader.cpp.i

core/experimental_vertices_model_loader.s: core/experimental_vertices_model_loader.cpp.s
.PHONY : core/experimental_vertices_model_loader.s

# target to generate assembly for a file
core/experimental_vertices_model_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/core/experimental_vertices_model_loader.cpp.s
.PHONY : core/experimental_vertices_model_loader.cpp.s

glad.o: glad.c.o
.PHONY : glad.o

# target to build an object file
glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/glad.c.o
.PHONY : glad.c.o

glad.i: glad.c.i
.PHONY : glad.i

# target to preprocess a source file
glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/glad.c.i
.PHONY : glad.c.i

glad.s: glad.c.s
.PHONY : glad.s

# target to generate assembly for a file
glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GLAD.dir/build.make CMakeFiles/GLAD.dir/glad.c.s
.PHONY : glad.c.s

includes/glm/detail/glm.o: includes/glm/detail/glm.cpp.o
.PHONY : includes/glm/detail/glm.o

# target to build an object file
includes/glm/detail/glm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/glm/detail/glm.cpp.o
.PHONY : includes/glm/detail/glm.cpp.o

includes/glm/detail/glm.i: includes/glm/detail/glm.cpp.i
.PHONY : includes/glm/detail/glm.i

# target to preprocess a source file
includes/glm/detail/glm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/glm/detail/glm.cpp.i
.PHONY : includes/glm/detail/glm.cpp.i

includes/glm/detail/glm.s: includes/glm/detail/glm.cpp.s
.PHONY : includes/glm/detail/glm.s

# target to generate assembly for a file
includes/glm/detail/glm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/glm/detail/glm.cpp.s
.PHONY : includes/glm/detail/glm.cpp.s

includes/imgui/backends/imgui_impl_glfw.o: includes/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : includes/imgui/backends/imgui_impl_glfw.o

# target to build an object file
includes/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : includes/imgui/backends/imgui_impl_glfw.cpp.o

includes/imgui/backends/imgui_impl_glfw.i: includes/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : includes/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
includes/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : includes/imgui/backends/imgui_impl_glfw.cpp.i

includes/imgui/backends/imgui_impl_glfw.s: includes/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : includes/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
includes/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : includes/imgui/backends/imgui_impl_glfw.cpp.s

includes/imgui/backends/imgui_impl_opengl3.o: includes/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : includes/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
includes/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : includes/imgui/backends/imgui_impl_opengl3.cpp.o

includes/imgui/backends/imgui_impl_opengl3.i: includes/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : includes/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
includes/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : includes/imgui/backends/imgui_impl_opengl3.cpp.i

includes/imgui/backends/imgui_impl_opengl3.s: includes/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : includes/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
includes/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : includes/imgui/backends/imgui_impl_opengl3.cpp.s

includes/imgui/examples/example_glfw_opengl3/main.o: includes/imgui/examples/example_glfw_opengl3/main.cpp.o
.PHONY : includes/imgui/examples/example_glfw_opengl3/main.o

# target to build an object file
includes/imgui/examples/example_glfw_opengl3/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/examples/example_glfw_opengl3/main.cpp.o
.PHONY : includes/imgui/examples/example_glfw_opengl3/main.cpp.o

includes/imgui/examples/example_glfw_opengl3/main.i: includes/imgui/examples/example_glfw_opengl3/main.cpp.i
.PHONY : includes/imgui/examples/example_glfw_opengl3/main.i

# target to preprocess a source file
includes/imgui/examples/example_glfw_opengl3/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/examples/example_glfw_opengl3/main.cpp.i
.PHONY : includes/imgui/examples/example_glfw_opengl3/main.cpp.i

includes/imgui/examples/example_glfw_opengl3/main.s: includes/imgui/examples/example_glfw_opengl3/main.cpp.s
.PHONY : includes/imgui/examples/example_glfw_opengl3/main.s

# target to generate assembly for a file
includes/imgui/examples/example_glfw_opengl3/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/examples/example_glfw_opengl3/main.cpp.s
.PHONY : includes/imgui/examples/example_glfw_opengl3/main.cpp.s

includes/imgui/examples/example_null/main.o: includes/imgui/examples/example_null/main.cpp.o
.PHONY : includes/imgui/examples/example_null/main.o

# target to build an object file
includes/imgui/examples/example_null/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/examples/example_null/main.cpp.o
.PHONY : includes/imgui/examples/example_null/main.cpp.o

includes/imgui/examples/example_null/main.i: includes/imgui/examples/example_null/main.cpp.i
.PHONY : includes/imgui/examples/example_null/main.i

# target to preprocess a source file
includes/imgui/examples/example_null/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/examples/example_null/main.cpp.i
.PHONY : includes/imgui/examples/example_null/main.cpp.i

includes/imgui/examples/example_null/main.s: includes/imgui/examples/example_null/main.cpp.s
.PHONY : includes/imgui/examples/example_null/main.s

# target to generate assembly for a file
includes/imgui/examples/example_null/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/examples/example_null/main.cpp.s
.PHONY : includes/imgui/examples/example_null/main.cpp.s

includes/imgui/imgui.o: includes/imgui/imgui.cpp.o
.PHONY : includes/imgui/imgui.o

# target to build an object file
includes/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/imgui.cpp.o
.PHONY : includes/imgui/imgui.cpp.o

includes/imgui/imgui.i: includes/imgui/imgui.cpp.i
.PHONY : includes/imgui/imgui.i

# target to preprocess a source file
includes/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/imgui.cpp.i
.PHONY : includes/imgui/imgui.cpp.i

includes/imgui/imgui.s: includes/imgui/imgui.cpp.s
.PHONY : includes/imgui/imgui.s

# target to generate assembly for a file
includes/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/imgui.cpp.s
.PHONY : includes/imgui/imgui.cpp.s

includes/imgui/imgui_demo.o: includes/imgui/imgui_demo.cpp.o
.PHONY : includes/imgui/imgui_demo.o

# target to build an object file
includes/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/imgui_demo.cpp.o
.PHONY : includes/imgui/imgui_demo.cpp.o

includes/imgui/imgui_demo.i: includes/imgui/imgui_demo.cpp.i
.PHONY : includes/imgui/imgui_demo.i

# target to preprocess a source file
includes/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/imgui_demo.cpp.i
.PHONY : includes/imgui/imgui_demo.cpp.i

includes/imgui/imgui_demo.s: includes/imgui/imgui_demo.cpp.s
.PHONY : includes/imgui/imgui_demo.s

# target to generate assembly for a file
includes/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/imgui_demo.cpp.s
.PHONY : includes/imgui/imgui_demo.cpp.s

includes/imgui/imgui_draw.o: includes/imgui/imgui_draw.cpp.o
.PHONY : includes/imgui/imgui_draw.o

# target to build an object file
includes/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/imgui_draw.cpp.o
.PHONY : includes/imgui/imgui_draw.cpp.o

includes/imgui/imgui_draw.i: includes/imgui/imgui_draw.cpp.i
.PHONY : includes/imgui/imgui_draw.i

# target to preprocess a source file
includes/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/imgui_draw.cpp.i
.PHONY : includes/imgui/imgui_draw.cpp.i

includes/imgui/imgui_draw.s: includes/imgui/imgui_draw.cpp.s
.PHONY : includes/imgui/imgui_draw.s

# target to generate assembly for a file
includes/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/imgui_draw.cpp.s
.PHONY : includes/imgui/imgui_draw.cpp.s

includes/imgui/imgui_tables.o: includes/imgui/imgui_tables.cpp.o
.PHONY : includes/imgui/imgui_tables.o

# target to build an object file
includes/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/imgui_tables.cpp.o
.PHONY : includes/imgui/imgui_tables.cpp.o

includes/imgui/imgui_tables.i: includes/imgui/imgui_tables.cpp.i
.PHONY : includes/imgui/imgui_tables.i

# target to preprocess a source file
includes/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/imgui_tables.cpp.i
.PHONY : includes/imgui/imgui_tables.cpp.i

includes/imgui/imgui_tables.s: includes/imgui/imgui_tables.cpp.s
.PHONY : includes/imgui/imgui_tables.s

# target to generate assembly for a file
includes/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/imgui_tables.cpp.s
.PHONY : includes/imgui/imgui_tables.cpp.s

includes/imgui/imgui_widgets.o: includes/imgui/imgui_widgets.cpp.o
.PHONY : includes/imgui/imgui_widgets.o

# target to build an object file
includes/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/imgui_widgets.cpp.o
.PHONY : includes/imgui/imgui_widgets.cpp.o

includes/imgui/imgui_widgets.i: includes/imgui/imgui_widgets.cpp.i
.PHONY : includes/imgui/imgui_widgets.i

# target to preprocess a source file
includes/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/imgui_widgets.cpp.i
.PHONY : includes/imgui/imgui_widgets.cpp.i

includes/imgui/imgui_widgets.s: includes/imgui/imgui_widgets.cpp.s
.PHONY : includes/imgui/imgui_widgets.s

# target to generate assembly for a file
includes/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/imgui_widgets.cpp.s
.PHONY : includes/imgui/imgui_widgets.cpp.s

includes/imgui/misc/cpp/imgui_stdlib.o: includes/imgui/misc/cpp/imgui_stdlib.cpp.o
.PHONY : includes/imgui/misc/cpp/imgui_stdlib.o

# target to build an object file
includes/imgui/misc/cpp/imgui_stdlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/misc/cpp/imgui_stdlib.cpp.o
.PHONY : includes/imgui/misc/cpp/imgui_stdlib.cpp.o

includes/imgui/misc/cpp/imgui_stdlib.i: includes/imgui/misc/cpp/imgui_stdlib.cpp.i
.PHONY : includes/imgui/misc/cpp/imgui_stdlib.i

# target to preprocess a source file
includes/imgui/misc/cpp/imgui_stdlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/misc/cpp/imgui_stdlib.cpp.i
.PHONY : includes/imgui/misc/cpp/imgui_stdlib.cpp.i

includes/imgui/misc/cpp/imgui_stdlib.s: includes/imgui/misc/cpp/imgui_stdlib.cpp.s
.PHONY : includes/imgui/misc/cpp/imgui_stdlib.s

# target to generate assembly for a file
includes/imgui/misc/cpp/imgui_stdlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/misc/cpp/imgui_stdlib.cpp.s
.PHONY : includes/imgui/misc/cpp/imgui_stdlib.cpp.s

includes/imgui/misc/fonts/binary_to_compressed_c.o: includes/imgui/misc/fonts/binary_to_compressed_c.cpp.o
.PHONY : includes/imgui/misc/fonts/binary_to_compressed_c.o

# target to build an object file
includes/imgui/misc/fonts/binary_to_compressed_c.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/misc/fonts/binary_to_compressed_c.cpp.o
.PHONY : includes/imgui/misc/fonts/binary_to_compressed_c.cpp.o

includes/imgui/misc/fonts/binary_to_compressed_c.i: includes/imgui/misc/fonts/binary_to_compressed_c.cpp.i
.PHONY : includes/imgui/misc/fonts/binary_to_compressed_c.i

# target to preprocess a source file
includes/imgui/misc/fonts/binary_to_compressed_c.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/misc/fonts/binary_to_compressed_c.cpp.i
.PHONY : includes/imgui/misc/fonts/binary_to_compressed_c.cpp.i

includes/imgui/misc/fonts/binary_to_compressed_c.s: includes/imgui/misc/fonts/binary_to_compressed_c.cpp.s
.PHONY : includes/imgui/misc/fonts/binary_to_compressed_c.s

# target to generate assembly for a file
includes/imgui/misc/fonts/binary_to_compressed_c.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/misc/fonts/binary_to_compressed_c.cpp.s
.PHONY : includes/imgui/misc/fonts/binary_to_compressed_c.cpp.s

includes/imgui/misc/freetype/imgui_freetype.o: includes/imgui/misc/freetype/imgui_freetype.cpp.o
.PHONY : includes/imgui/misc/freetype/imgui_freetype.o

# target to build an object file
includes/imgui/misc/freetype/imgui_freetype.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/misc/freetype/imgui_freetype.cpp.o
.PHONY : includes/imgui/misc/freetype/imgui_freetype.cpp.o

includes/imgui/misc/freetype/imgui_freetype.i: includes/imgui/misc/freetype/imgui_freetype.cpp.i
.PHONY : includes/imgui/misc/freetype/imgui_freetype.i

# target to preprocess a source file
includes/imgui/misc/freetype/imgui_freetype.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/misc/freetype/imgui_freetype.cpp.i
.PHONY : includes/imgui/misc/freetype/imgui_freetype.cpp.i

includes/imgui/misc/freetype/imgui_freetype.s: includes/imgui/misc/freetype/imgui_freetype.cpp.s
.PHONY : includes/imgui/misc/freetype/imgui_freetype.s

# target to generate assembly for a file
includes/imgui/misc/freetype/imgui_freetype.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/includes/imgui/misc/freetype/imgui_freetype.cpp.s
.PHONY : includes/imgui/misc/freetype/imgui_freetype.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/main.cpp.s
.PHONY : main.cpp.s

stb_image.o: stb_image.cpp.o
.PHONY : stb_image.o

# target to build an object file
stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/stb_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STB_IMAGE.dir/build.make CMakeFiles/STB_IMAGE.dir/stb_image.cpp.o
.PHONY : stb_image.cpp.o

stb_image.i: stb_image.cpp.i
.PHONY : stb_image.i

# target to preprocess a source file
stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/stb_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STB_IMAGE.dir/build.make CMakeFiles/STB_IMAGE.dir/stb_image.cpp.i
.PHONY : stb_image.cpp.i

stb_image.s: stb_image.cpp.s
.PHONY : stb_image.s

# target to generate assembly for a file
stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SillyEngine.dir/build.make CMakeFiles/SillyEngine.dir/stb_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STB_IMAGE.dir/build.make CMakeFiles/STB_IMAGE.dir/stb_image.cpp.s
.PHONY : stb_image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GLAD"
	@echo "... STB_IMAGE"
	@echo "... SillyEngine"
	@echo "... CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... build/CMakeFiles/3.24.0/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... cmake-build-debug/CMakeFiles/3.13.4/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... core/Engine.o"
	@echo "... core/Engine.i"
	@echo "... core/Engine.s"
	@echo "... core/Framebuffer.o"
	@echo "... core/Framebuffer.i"
	@echo "... core/Framebuffer.s"
	@echo "... core/ImageLoader.o"
	@echo "... core/ImageLoader.i"
	@echo "... core/ImageLoader.s"
	@echo "... core/Input.o"
	@echo "... core/Input.i"
	@echo "... core/Input.s"
	@echo "... core/Mesh.o"
	@echo "... core/Mesh.i"
	@echo "... core/Mesh.s"
	@echo "... core/Model.o"
	@echo "... core/Model.i"
	@echo "... core/Model.s"
	@echo "... core/Shader.o"
	@echo "... core/Shader.i"
	@echo "... core/Shader.s"
	@echo "... core/Window.o"
	@echo "... core/Window.i"
	@echo "... core/Window.s"
	@echo "... core/components/Camera.o"
	@echo "... core/components/Camera.i"
	@echo "... core/components/Camera.s"
	@echo "... core/experimental_vertices_model_loader.o"
	@echo "... core/experimental_vertices_model_loader.i"
	@echo "... core/experimental_vertices_model_loader.s"
	@echo "... glad.o"
	@echo "... glad.i"
	@echo "... glad.s"
	@echo "... includes/glm/detail/glm.o"
	@echo "... includes/glm/detail/glm.i"
	@echo "... includes/glm/detail/glm.s"
	@echo "... includes/imgui/backends/imgui_impl_glfw.o"
	@echo "... includes/imgui/backends/imgui_impl_glfw.i"
	@echo "... includes/imgui/backends/imgui_impl_glfw.s"
	@echo "... includes/imgui/backends/imgui_impl_opengl3.o"
	@echo "... includes/imgui/backends/imgui_impl_opengl3.i"
	@echo "... includes/imgui/backends/imgui_impl_opengl3.s"
	@echo "... includes/imgui/examples/example_glfw_opengl3/main.o"
	@echo "... includes/imgui/examples/example_glfw_opengl3/main.i"
	@echo "... includes/imgui/examples/example_glfw_opengl3/main.s"
	@echo "... includes/imgui/examples/example_null/main.o"
	@echo "... includes/imgui/examples/example_null/main.i"
	@echo "... includes/imgui/examples/example_null/main.s"
	@echo "... includes/imgui/imgui.o"
	@echo "... includes/imgui/imgui.i"
	@echo "... includes/imgui/imgui.s"
	@echo "... includes/imgui/imgui_demo.o"
	@echo "... includes/imgui/imgui_demo.i"
	@echo "... includes/imgui/imgui_demo.s"
	@echo "... includes/imgui/imgui_draw.o"
	@echo "... includes/imgui/imgui_draw.i"
	@echo "... includes/imgui/imgui_draw.s"
	@echo "... includes/imgui/imgui_tables.o"
	@echo "... includes/imgui/imgui_tables.i"
	@echo "... includes/imgui/imgui_tables.s"
	@echo "... includes/imgui/imgui_widgets.o"
	@echo "... includes/imgui/imgui_widgets.i"
	@echo "... includes/imgui/imgui_widgets.s"
	@echo "... includes/imgui/misc/cpp/imgui_stdlib.o"
	@echo "... includes/imgui/misc/cpp/imgui_stdlib.i"
	@echo "... includes/imgui/misc/cpp/imgui_stdlib.s"
	@echo "... includes/imgui/misc/fonts/binary_to_compressed_c.o"
	@echo "... includes/imgui/misc/fonts/binary_to_compressed_c.i"
	@echo "... includes/imgui/misc/fonts/binary_to_compressed_c.s"
	@echo "... includes/imgui/misc/freetype/imgui_freetype.o"
	@echo "... includes/imgui/misc/freetype/imgui_freetype.i"
	@echo "... includes/imgui/misc/freetype/imgui_freetype.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... stb_image.o"
	@echo "... stb_image.i"
	@echo "... stb_image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

